# Generated by Django 5.2.7 on 2025-11-19 18:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='mobile',
            field=models.CharField(db_index=True, max_length=15, validators=[django.core.validators.RegexValidator(message='Phone number must be: +989XXXXXXXXX or 989XXXXXXXXX', regex='^\\+?989\\d{9}$')]),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='mobile',
            field=models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator(message='Phone number must be: +989XXXXXXXXX or 989XXXXXXXXX', regex='^\\+?989\\d{9}$')]),
        ),
        migrations.AlterField(
            model_name='user',
            name='mobile',
            field=models.CharField(db_index=True, max_length=15, unique=True, validators=[django.core.validators.RegexValidator(message='Phone number must be: +989XXXXXXXXX or 989XXXXXXXXX', regex='^\\+?989\\d{9}$')]),
        ),
    ]
